services:
  db:
    container_name: jerry_db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=jerry_api_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql


  api:
    container_name: jerry_api
    build: 
      context: .
      dockerfile: ./api/Dockerfile.dev
    environment:
      db_host: db
      db_port: 5432
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/api
    depends_on:
      - db


  k6:
    image: grafana/k6:master
    
    volumes:
      - ./k6:/scripts
    command: run /scripts/script.ts
    depends_on:
      - api

      



volumes:
  db_data: